### ISSUE TITLE
The import fr.inria.sniffer.detector cannot be resolved

### ISSUE THREAD

**Issue by nirajnagrale** [HabchiSarra/Sniffer#11]
./gradlew build -S ==> upon executing this we see in the verbose that the errors are generated from the unresolved import of the QueryEngine are we missing something? or there are other dependencies the gradle needs to be aware of ?

**Comment by aveuiller** [comment]
Hello,

It seems that you forgot to pull the submodule dependencies using `git submodule init && git submodule update`.

As you already tried to build the project, you may have created the submodule destination directories, so don't forget to delete them beforehand `rm -rf SmellDetector CSVSmellTracker GitHubMiner`.

**Comment by nirajnagrale** [comment]
After rm -rf SmellDetector CSVSmellTracker GitHubMiner i ran command git submodule init && git submodule update it following gives error
Cloning into '/home/niraj/sniffer/Sniffer/CSVSmellTracker'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HabchiSarra/CSVSmellTracker.git' into submodule path '/home/niraj/sniffer/Sniffer/CSVSmellTracker' failed
Failed to clone 'CSVSmellTracker'. Retry scheduled
Cloning into '/home/niraj/sniffer/Sniffer/GitHubMiner'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HabchiSarra/GitHubMiner.git' into submodule path '/home/niraj/sniffer/Sniffer/GitHubMiner' failed
Failed to clone 'GitHubMiner'. Retry scheduled
Cloning into '/home/niraj/sniffer/Sniffer/SmellDetector'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HabchiSarra/SmellDetector.git' into submodule path '/home/niraj/sniffer/Sniffer/SmellDetector' failed
Failed to clone 'SmellDetector'. Retry scheduled
Cloning into '/home/niraj/sniffer/Sniffer/CSVSmellTracker'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HabchiSarra/CSVSmellTracker.git' into submodule path '/home/niraj/sniffer/Sniffer/CSVSmellTracker' failed
Failed to clone 'CSVSmellTracker' a second time, aborting

Am I missing anything?

**Comment by aveuiller** [comment]
Hello,

As the project was closed-sourced for a while, the submodule configuration expected you to have an ssh key configured on GitHub by using the git protocol.

I changed the submodule configuration to clone through https so if you pull the last commit on develop it should work correctly for you.

**Comment by nirajnagrale** [comment]
When i run projectLooper.sh I get this following error:

java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:137)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:130)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:107)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
        at fr.inria.sniffer.detector.neo4j.DatabaseManager.start(DatabaseManager.java:40)
        at fr.inria.sniffer.detector.neo4j.ModelToGraph.<init>(ModelToGraph.java:71)
        at fr.inria.sniffer.detector.analyzer.Main.runAnalysis(Main.java:120)
        at fr.inria.sniffer.detector.analyzer.Main.main(Main.java:72)

in debug.log file i get this
2023-03-09 19:02:29.804+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.directories.neo4j_home=/home/usr/sniffer/Sniffer/CommitLooper/repositories/2048-android/../../allDatabases/2048-android/databases/graph.db
2023-03-09 19:02:29.804+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.edition=community
2023-03-09 19:02:29.804+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.ephemeral=false

What is wrong?
