### ISSUE TITLE
error on analyzing the project 

### ISSUE THREAD

**Issue by nirajnagrale** [HabchiSarra/Sniffer#12]
When i run projectLooper.sh I get this following error:

java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory
at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:137)
at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:130)
at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:107)
at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
at fr.inria.sniffer.detector.neo4j.DatabaseManager.start(DatabaseManager.java:40)
at fr.inria.sniffer.detector.neo4j.ModelToGraph.(ModelToGraph.java:71)
at fr.inria.sniffer.detector.analyzer.Main.runAnalysis(Main.java:120)
at fr.inria.sniffer.detector.analyzer.Main.main(Main.java:72)

in debug.log file i get this

2023-03-09 19:02:29.804+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.directories.neo4j_home=/home/usr/sniffer/Sniffer/CommitLooper/repositories/2048-android/../../allDatabases/2048-android/databases/graph.db
2023-03-09 19:02:29.804+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.edition=community
2023-03-09 19:02:29.804+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.ephemeral=false

What is wrong?

**Comment by aveuiller** [comment]
Hello,

This project is quite ancient and was created using java 8. If you are using a more recent version you may want to downgrade your java version.

From my tests, java 11 seems to be working correctly with a few warnings.

Any PR is welcome if you aim to upgrade the dependencies to support recent versions though. :)
