### ISSUE TITLE
Errors while analyzing project's commits

### ISSUE THREAD

**Issue by Mohannadcse** [HabchiSarra/Sniffer#5]
I've analyzed the commits of several github projects, I received the following errors while analyzing the commits of [this github project](https://github.com/woffs/tazapp-android). 

```
spoon.compiler.ModelBuildingException: The type BuildTypeProvider is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:612)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:37)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:99)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:266)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:444)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:388)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:340)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:129)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.Launcher.buildModel(Launcher.java:769)
	at fr.inria.sniffer.detector.analyzer.MainProcessor.process(MainProcessor.java:59)
	at fr.inria.sniffer.detector.analyzer.Main.runAnalysis(Main.java:104)
	at fr.inria.sniffer.detector.analyzer.Main.main(Main.java:70)
```

I also received the following errors while analyzing the commits of [this github project](https://github.com/playmusicexporter/playmusicexporter)

````
2019-07-11 20:47:19 ERROR  JDTTreeBuilder:203 - Could not find declaration for variable pager at (/Users/think/Downloads/codeSmell/Sniffer/CommitLooper/repositories/Exporter/playmusicexporter/src/main/java/re/jcg/playmusicexporter/activities/Intro.java:158)
	2019-07-11 20:47:19 ERROR  JDTTreeBuilder:203 - Could not find declaration for variable pager at (/Users/think/Downloads/codeSmell/Sniffer/CommitLooper/repositories/Exporter/playmusicexporter/src/main/java/re/jcg/playmusicexporter/activities/Intro.java:172)
	2019-07-11 20:47:19 ERROR  JDTTreeBuilder:203 - Could not find declaration for variable pager at (/Users/think/Downloads/codeSmell/Sniffer/CommitLooper/repositories/Exporter/playmusicexporter/src/main/java/re/jcg/playmusicexporter/activities/Intro.java:172)
```

**Comment by aveuiller** [comment]
Hello @Mohannadcse,

Thanks for the report, we are currently looking for the root causes of the two bugs.

They seem to be different but both come from our use of JDT:

- `woffs/tazapp-android`: It seems that the same class is declared in both the `debug` and `release` flavour. We will add an include/exclude system to be able to avoid these issues.
- `playmusicexporter/playmusicexporter`: A first look makes me think that the class from the stacktrace is using an attribute defined in a superclass only present in an external library. We don't fetch the library source code for analysis so JDT seems lost. We may have a way to make it accept this kind of situations.

We will try to fix the situations and come back to you ASAP.
